import Header from './components/Header'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Metaview Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${montserrat.className} debug-screens min-h-screen flex flex-col bg-light container`}
      >
        <Header />
        <main className='flex-1 relative top-40 px-12'>{children}</main>
      </body>
    </html>
  )
}
